site_name: 155GISE
nav:
  - Course information: index.md
  - Practicals:
      - Practical 1: practicals/practical1.md
      - Practical 2: practicals/practical2.md
      - Practical 3: practicals/practical3.md
      - Practical 4: practicals/practical4.md
      - Practical 5: practicals/practical5.md
  # - Data: data.md
  # - Hodnocení: hodnoceni.md
  # - Semestrální práce: semestralka.md
  # - Výuková videa: videa.md
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CTUGeomatics
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geomatics.ctu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geomatics.ctu
copyright: <a href="https://geomatics.fsv.cvut.cz" target="_blank">Katedra geomatiky</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;2023
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
